CREATE TABLE `analyses` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`facility_name` text NOT NULL,
	`created_at_utc` text NOT NULL,
	`analysis_time_local` text NOT NULL,
	`analysis_time_utc` text NOT NULL,
	`iana_timezone` text NOT NULL,
	`latitude` real NOT NULL,
	`longitude` real NOT NULL,
	`facility_radius_m` integer NOT NULL,
	`it_load_mw` real,
	`baseline_pue` real,
	`cooling_configuration` text NOT NULL,
	`save_for_history` integer NOT NULL,
	`allow_shared_model_improvement` integer NOT NULL,
	`status` text NOT NULL,
	`center_temperature_c` real,
	`core_mean_temperature_c` real,
	`core_max_temperature_c` real,
	`core_p90_temperature_c` real,
	`core_temperature_std_c` real,
	`near_mean_temperature_c` real,
	`background_mean_temperature_c` real,
	`core_minus_background_c` real,
	`hotspot_fraction` real,
	`relative_humidity_percent` real,
	`wet_bulb_temperature_c` real,
	`cooling_ratio` real,
	`cooling_mw` real,
	`weather_uplift` real,
	`incremental_cooling_mw` real,
	`scenario_pue` real,
	`environmental_exposure_score` real,
	`environmental_exposure_level` text,
	`confidence_level` text,
	`summary` text,
	`model_id` text NOT NULL,
	`heatmap_activity_ids_json` text,
	`environment_activity_id` text,
	`api_timestamp` text,
	`data_quality_json` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_analyses_customer_created` ON `analyses` (`customer_id`,`created_at_utc`);--> statement-breakpoint
CREATE INDEX `idx_analyses_customer_facility` ON `analyses` (`customer_id`,`facility_name`);