import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const analyses = sqliteTable(
  "analyses",
  {
    id: text("id").primaryKey(),
    customerId: text("customer_id").notNull(),
    facilityName: text("facility_name").notNull(),
    createdAtUtc: text("created_at_utc").notNull(),
    analysisTimeLocal: text("analysis_time_local").notNull(),
    analysisTimeUtc: text("analysis_time_utc").notNull(),
    ianaTimezone: text("iana_timezone").notNull(),
    latitude: real("latitude").notNull(),
    longitude: real("longitude").notNull(),
    facilityRadiusM: integer("facility_radius_m").notNull(),
    itLoadMw: real("it_load_mw"),
    itLoadFraction: real("it_load_fraction").notNull(),
    loadStateSupport: text("load_state_support").notNull().default("unknown"),
    loadStateTrainingHours: integer("load_state_training_hours").notNull().default(0),
    baselinePue: real("baseline_pue"),
    coolingConfiguration: text("cooling_configuration").notNull(),
    saveForHistory: integer("save_for_history", { mode: "boolean" }).notNull(),
    allowSharedModelImprovement: integer("allow_shared_model_improvement", { mode: "boolean" }).notNull(),
    status: text("status").notNull(),
    centerTemperatureC: real("center_temperature_c"),
    coreMeanTemperatureC: real("core_mean_temperature_c"),
    coreMaxTemperatureC: real("core_max_temperature_c"),
    coreP90TemperatureC: real("core_p90_temperature_c"),
    coreTemperatureStdC: real("core_temperature_std_c"),
    nearMeanTemperatureC: real("near_mean_temperature_c"),
    backgroundMeanTemperatureC: real("background_mean_temperature_c"),
    coreMinusBackgroundC: real("core_minus_background_c"),
    hotspotFraction: real("hotspot_fraction"),
    relativeHumidityPercent: real("relative_humidity_percent"),
    wetBulbTemperatureC: real("wet_bulb_temperature_c"),
    coolingRatio: real("cooling_ratio"),
    coolingMw: real("cooling_mw"),
    weatherUplift: real("weather_uplift"),
    incrementalCoolingMw: real("incremental_cooling_mw"),
    scenarioPue: real("scenario_pue"),
    environmentalExposureScore: real("environmental_exposure_score"),
    environmentalExposureLevel: text("environmental_exposure_level"),
    confidenceLevel: text("confidence_level"),
    summary: text("summary"),
    modelId: text("model_id").notNull(),
    heatmapActivityIdsJson: text("heatmap_activity_ids_json"),
    environmentActivityId: text("environment_activity_id"),
    apiTimestamp: text("api_timestamp"),
    dataQualityJson: text("data_quality_json").notNull(),
  },
  (table) => [
    index("idx_analyses_customer_created").on(table.customerId, table.createdAtUtc),
    index("idx_analyses_customer_facility").on(table.customerId, table.facilityName),
  ],
);
